"""fix_missing_tables

Revision ID: f13d32166ef4
Revises: 52bbc9a8469b
Create Date: 2025-05-08 23:43:02.698755

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f13d32166ef4'
down_revision = '52bbc9a8469b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
